/**
 * Report Model for user/moderation queue
 * Handles user reports for inappropriate content, spam, harassment, etc.
 * 
 * @module models/Report
 */

const mongoose = require('mongoose');

// ============================================
// Constants
// ============================================

const REPORT_STATUS = {
  PENDING: 'pending',
  REVIEWING: 'reviewing',
  RESOLVED: 'resolved',
  DISMISSED: 'dismissed'
};

const REPORT_REASONS = {
  SPAM: 'spam',
  INAPPROPRIATE: 'inappropriate',
  HARASSMENT: 'harassment',
  FAKE_ACCOUNT: 'fake_account',
  COPYRIGHT: 'copyright',
  OTHER: 'other'
};

const REPORT_ACTIONS = {
  NONE: 'none',
  WARN: 'warn',
  SUSPEND: 'suspend',
  BAN: 'ban',
  DELETE_POST: 'delete_post',
  DELETE_COMMENT: 'delete_comment'
};

// ============================================
// Schema Definition
// ============================================

const reportSchema = new mongoose.Schema(
  {
    // User who submitted the report
    reporterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },
    
    // User being reported (if reporting a user)
    reportedUserId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      index: true,
      sparse: true
    },
    
    // Post being reported (if reporting a post)
    reportedPostId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CommunityPost',
      index: true,
      sparse: true
    },
    
    // Comment being reported (if reporting a comment)
    reportedCommentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CommunityComment',
      index: true,
      sparse: true
    },
    
    // Reason for report
    reason: {
      type: String,
      enum: Object.values(REPORT_REASONS),
      required: true,
      index: true
    },
    
    // Additional description/evidence
    description: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: null
    },
    
    // Current status of the report
    status: {
      type: String,
      enum: Object.values(REPORT_STATUS),
      default: REPORT_STATUS.PENDING,
      index: true
    },
    
    // Admin who reviewed the report
    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null
    },
    
    // Timestamp when reviewed
    reviewedAt: {
      type: Date,
      default: null
    },
    
    // Action taken by admin
    actionTaken: {
      type: String,
      enum: Object.values(REPORT_ACTIONS),
      default: REPORT_ACTIONS.NONE
    },
    
    // Resolution notes from admin
    resolution: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: null
    },
    
    // Priority level for moderation queue
    priority: {
      type: Number,
      default: 1,
      min: 1,
      max: 5,
      index: true
    },
    
    // Whether the report was auto-generated (e.g., by AI moderation)
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    
    // Auto-moderation confidence score (0-100)
    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
      default: null
    }
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
);

// ============================================
// Indexes
// ============================================

// Moderation queue queries
reportSchema.index({ status: 1, priority: -1, createdAt: 1 });

// Reporter lookup
reportSchema.index({ reporterId: 1, createdAt: -1 });

// Reported user lookup
reportSchema.index({ reportedUserId: 1, status: 1 });

// Reported post lookup
reportSchema.index({ reportedPostId: 1 });

// Duplicate prevention
reportSchema.index(
  { reporterId: 1, reportedUserId: 1, reportedPostId: 1, reportedCommentId: 1, status: 1 },
  { partialFilterExpression: { status: { $in: ['pending', 'reviewing'] } } }
);

// Date range queries for analytics
reportSchema.index({ createdAt: -1 });

// ============================================
// Virtual Fields
// ============================================

/**
 * Check if report is pending
 */
reportSchema.virtual('isPending').get(function() {
  return this.status === REPORT_STATUS.PENDING;
});

/**
 * Check if report has been resolved
 */
reportSchema.virtual('isResolved').get(function() {
  return this.status === REPORT_STATUS.RESOLVED || this.status === REPORT_STATUS.DISMISSED;
});

/**
 * Get target type (user, post, or comment)
 */
reportSchema.virtual('targetType').get(function() {
  if (this.reportedUserId) return 'user';
  if (this.reportedPostId) return 'post';
  if (this.reportedCommentId) return 'comment';
  return 'unknown';
});

/**
 * Get formatted reason label
 */
reportSchema.virtual('reasonLabel').get(function() {
  const labels = {
    [REPORT_REASONS.SPAM]: 'Spam or misleading',
    [REPORT_REASONS.INAPPROPRIATE]: 'Inappropriate content',
    [REPORT_REASONS.HARASSMENT]: 'Harassment or bullying',
    [REPORT_REASONS.FAKE_ACCOUNT]: 'Fake account / impersonation',
    [REPORT_REASONS.COPYRIGHT]: 'Copyright violation',
    [REPORT_REASONS.OTHER]: 'Other'
  };
  return labels[this.reason] || this.reason;
});

/**
 * Get time since report was created
 */
reportSchema.virtual('timeAgo').get(function() {
  const seconds = Math.floor((new Date() - this.createdAt) / 1000);
  if (seconds < 60) return `${seconds} seconds ago`;
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes} minute${minutes !== 1 ? 's' : ''} ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hour${hours !== 1 ? 's' : ''} ago`;
  const days = Math.floor(hours / 24);
  return `${days} day${days !== 1 ? 's' : ''} ago`;
});

// ============================================
// Instance Methods
// ============================================

/**
 * Mark report as under review
 * @param {string} adminId - ID of the admin reviewing
 * @returns {Promise<Report>}
 */
reportSchema.methods.startReview = async function(adminId) {
  this.status = REPORT_STATUS.REVIEWING;
  this.reviewedBy = adminId;
  await this.save();
  return this;
};

/**
 * Resolve report with action
 * @param {Object} params - Resolution parameters
 * @returns {Promise<Report>}
 */
reportSchema.methods.resolve = async function({ adminId, action, resolution }) {
  this.status = REPORT_STATUS.RESOLVED;
  this.reviewedBy = adminId;
  this.reviewedAt = new Date();
  this.actionTaken = action || REPORT_ACTIONS.NONE;
  this.resolution = resolution || null;
  await this.save();
  return this;
};

/**
 * Dismiss report (no action taken)
 * @param {Object} params - Dismissal parameters
 * @returns {Promise<Report>}
 */
reportSchema.methods.dismiss = async function({ adminId, resolution }) {
  this.status = REPORT_STATUS.DISMISSED;
  this.reviewedBy = adminId;
  this.reviewedAt = new Date();
  this.resolution = resolution || 'No violation found';
  await this.save();
  return this;
};

/**
 * Escalate report priority
 * @returns {Promise<Report>}
 */
reportSchema.methods.escalate = async function() {
  this.priority = Math.min(5, this.priority + 1);
  await this.save();
  return this;
};

// ============================================
// Static Methods
// ============================================

/**
 * Get pending reports for moderation queue
 * @param {Object} options - Pagination options
 * @returns {Promise<Object>}
 */
reportSchema.statics.getModerationQueue = async function(options = {}) {
  const { page = 1, limit = 20, priority = null } = options;
  const skip = (page - 1) * limit;
  const effectiveLimit = Math.min(limit, 100);
  
  const query = { status: { $in: [REPORT_STATUS.PENDING, REPORT_STATUS.REVIEWING] } };
  if (priority) query.priority = priority;
  
  const [reports, total] = await Promise.all([
    this.find(query)
      .sort({ priority: -1, createdAt: 1 })
      .skip(skip)
      .limit(effectiveLimit)
      .populate('reporterId', 'email uniqueCode role profile.stageName profile.companyName profile.avatarUrl')
      .populate('reportedUserId', 'email uniqueCode role profile.stageName profile.companyName profile.avatarUrl')
      .populate('reportedPostId', 'caption mediaUrl mediaType createdAt likeCount commentCount')
      .lean(),
    this.countDocuments(query)
  ]);
  
  return {
    reports,
    pagination: {
      page,
      limit: effectiveLimit,
      total,
      pages: Math.ceil(total / effectiveLimit),
      hasMore: skip + reports.length < total
    }
  };
};

/**
 * Get report statistics
 * @returns {Promise<Object>}
 */
reportSchema.statics.getStats = async function() {
  const [byStatus, byReason, todayCount, pendingHighPriority] = await Promise.all([
    this.aggregate([
      { $group: { _id: '$status', count: { $sum: 1 } } }
    ]),
    this.aggregate([
      { $group: { _id: '$reason', count: { $sum: 1 } } },
      { $sort: { count: -1 } }
    ]),
    this.countDocuments({
      createdAt: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) }
    }),
    this.countDocuments({
      status: { $in: [REPORT_STATUS.PENDING, REPORT_STATUS.REVIEWING] },
      priority: { $gte: 3 }
    })
  ]);
  
  const statusMap = {};
  byStatus.forEach(s => { statusMap[s._id] = s.count; });
  
  return {
    byStatus: {
      pending: statusMap[REPORT_STATUS.PENDING] || 0,
      reviewing: statusMap[REPORT_STATUS.REVIEWING] || 0,
      resolved: statusMap[REPORT_STATUS.RESOLVED] || 0,
      dismissed: statusMap[REPORT_STATUS.DISMISSED] || 0
    },
    byReason,
    todayCount,
    pendingHighPriority,
    totalReports: await this.countDocuments()
  };
};

/**
 * Check if user has already reported content
 * @param {string} reporterId - User ID
 * @param {Object} target - Target object with userId/postId/commentId
 * @returns {Promise<boolean>}
 */
reportSchema.statics.hasReported = async function(reporterId, target) {
  const query = {
    reporterId,
    status: { $in: [REPORT_STATUS.PENDING, REPORT_STATUS.REVIEWING] }
  };
  
  if (target.userId) query.reportedUserId = target.userId;
  else if (target.postId) query.reportedPostId = target.postId;
  else if (target.commentId) query.reportedCommentId = target.commentId;
  else return false;
  
  const report = await this.findOne(query);
  return !!report;
};

/**
 * Auto-resolve old pending reports
 * @param {number} days - Days after which to auto-dismiss
 * @returns {Promise<number>}
 */
reportSchema.statics.autoResolveOldReports = async function(days = 30) {
  const cutoffDate = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const result = await this.updateMany(
    {
      status: REPORT_STATUS.PENDING,
      createdAt: { $lt: cutoffDate }
    },
    {
      status: REPORT_STATUS.DISMISSED,
      resolution: 'Auto-dismissed due to age',
      reviewedAt: new Date()
    }
  );
  return result.modifiedCount;
};

// ============================================
// Pre-save Hooks
// ============================================

/**
 * Set priority based on reason and description
 */
reportSchema.pre('save', function(next) {
  // Calculate priority based on reason
  const priorityMap = {
    [REPORT_REASONS.HARASSMENT]: 5,
    [REPORT_REASONS.COPYRIGHT]: 4,
    [REPORT_REASONS.INAPPROPRIATE]: 3,
    [REPORT_REASONS.FAKE_ACCOUNT]: 3,
    [REPORT_REASONS.SPAM]: 2,
    [REPORT_REASONS.OTHER]: 1
  };
  
  // Set priority if not already set or if it's a new report
  if (this.isNew || !this.priority) {
    this.priority = priorityMap[this.reason] || 1;
  }
  
  next();
});

// ============================================
// Exports
// ============================================

module.exports = mongoose.model('Report', reportSchema);
module.exports.REPORT_STATUS = REPORT_STATUS;
module.exports.REPORT_REASONS = REPORT_REASONS;
module.exports.REPORT_ACTIONS = REPORT_ACTIONS;
